import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import logoSrc from '../lib/logoSrc';

function PostCard({ post }) {
  let images = [];
  try { images = JSON.parse(post.image_urls || '[]'); } catch {}

  return (
    <div className="rounded-2xl overflow-hidden bg-white/[0.03] border border-white/5">
      {/* Images */}
      {images.length > 0 && (
        <div className={images.length > 1 ? 'grid grid-cols-2 gap-0.5' : ''}>
          {images.map((url, i) => (
            <img
              key={i}
              src={url}
              alt={`Day ${post.day_number} slide ${i + 1}`}
              className="w-full aspect-square object-cover"
            />
          ))}
        </div>
      )}

      {/* Content */}
      <div className="p-5 space-y-3">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-white/50 bg-white/5 px-2.5 py-1 rounded-full">
            Day {post.day_number}
          </span>
          <span className="text-xs text-white/30">{post.post_type}</span>
          {post.pillar && (
            <span className="text-xs text-[#2dd4bf]/60 bg-[#2dd4bf]/10 px-2 py-0.5 rounded-full">
              {post.pillar}
            </span>
          )}
        </div>

        <h3 className="text-sm font-semibold text-white/80">{post.concept}</h3>

        <p className="text-sm text-white/50 whitespace-pre-line leading-relaxed">
          {post.caption}
        </p>

        {post.hashtags && (
          <p className="text-xs text-[#3b82f6]/50">{post.hashtags}</p>
        )}
      </div>
    </div>
  );
}

export default function CampaignPreview() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetch(`/api/preview/${id}`)
      .then(r => {
        if (!r.ok) throw new Error('Campaign not found');
        return r.json();
      })
      .then(d => { setData(d); setLoading(false); })
      .catch(e => { setError(e.message); setLoading(false); });
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-navy flex items-center justify-center">
        <p className="text-white/30 text-sm">Loading preview...</p>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen bg-navy flex items-center justify-center">
        <p className="text-white/40 text-sm">{error || 'Preview not available'}</p>
      </div>
    );
  }

  const postsWithImages = data.posts.filter(p => {
    try { return JSON.parse(p.image_urls || '[]').length > 0; } catch { return false; }
  });
  const totalImages = data.posts.reduce((acc, p) => {
    try { return acc + JSON.parse(p.image_urls || '[]').length; } catch { return acc; }
  }, 0);

  return (
    <div className="min-h-screen bg-navy">
      {/* Header */}
      <div className="border-b border-white/5">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <div className="flex items-center gap-4 mb-4">
            {data.client_logo && (
              <img src={logoSrc(data.client_logo)} alt="" className="w-12 h-12 rounded-xl object-cover bg-white/5" />
            )}
            <div>
              <h1 className="text-2xl font-bold text-white">{data.client_name}</h1>
              <p className="text-white/30 text-sm">Social Media Content Preview</p>
            </div>
          </div>
          <div className="flex gap-6 text-sm">
            <div>
              <span className="text-white/30">Month: </span>
              <span className="text-white/60">{data.month || '—'}</span>
            </div>
            <div>
              <span className="text-white/30">Theme: </span>
              <span className="text-white/60">{data.theme || '—'}</span>
            </div>
            <div>
              <span className="text-white/30">Posts: </span>
              <span className="text-white/60">{data.posts.length}</span>
            </div>
            <div>
              <span className="text-white/30">Images: </span>
              <span className="text-white/60">{totalImages}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Posts grid */}
      <div className="max-w-5xl mx-auto px-6 py-8">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {data.posts.map(post => (
            <PostCard key={post.day_number} post={post} />
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 text-center">
          <p className="text-white/15 text-xs">
            Generated by VO360 Command Center
          </p>
        </div>
      </div>
    </div>
  );
}
